import {registerDefaults} from "./com/domwires/core/registerDefaults";

export * from "./com/domwires/core/Global";
export * from "./com/domwires/core/Enum";
export * from "./com/domwires/core/Decorators";
export * from "./com/domwires/core/registerDefaults";
export * from "./com/domwires/core/app/AbstractApp";
export * from "./com/domwires/core/common/IDisposable";
export * from "./com/domwires/core/common/AbstractDisposable";
export * from "./com/domwires/core/di/Decorators";
export * from "./com/domwires/core/di/IDependencyContainer";
export * from "./com/domwires/core/di/DependencyContainer";
export * from "./com/domwires/core/di/LazyRegistry";
export * from "./com/domwires/core/factory/IFactory";
export * from "./com/domwires/core/mvc/command/ICommand";
export * from "./com/domwires/core/mvc/command/IAsyncCommand";
export * from "./com/domwires/core/mvc/command/AbstractCommand";
export * from "./com/domwires/core/mvc/command/AbstractAsyncCommand";
export * from "./com/domwires/core/mvc/command/AbstractGuards";
export * from "./com/domwires/core/mvc/command/IGuards";
export * from "./com/domwires/core/mvc/command/ICommandMapper";
export * from "./com/domwires/core/mvc/context/IContext";
export * from "./com/domwires/core/mvc/context/AbstractContext";
export * from "./com/domwires/core/mvc/hierarchy/IHierarchyObject";
export * from "./com/domwires/core/mvc/hierarchy/AbstractHierarchyObject";
export * from "./com/domwires/core/mvc/hierarchy/IHierarchyObjectContainer";
export * from "./com/domwires/core/mvc/message/IMessageDispatcher";
export * from "./com/domwires/core/utils/ArrayUtils";
export * from "./com/domwires/logger/ILogger";

registerDefaults();
