name: Test

on: [push]

jobs:
  build:
    strategy:
      matrix:
        node: [14.x]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-v${{ matrix.node }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-v${{ matrix.node }}-
      - run: npm install
      - run: npm test
      - run: npm run eslint-setup
      - run: npm run eslint-run