name: Test

on: [push]

jobs:
  build:
    strategy:
      matrix:
        node: [14.x]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          path: ~/.npm
      - run: npm install
      - run: npm test
      - run: npm run eslint-setup
      - run: npm run eslint-run