name: Test

on: [push]

jobs:
  build:
    strategy:
      matrix:
        node: ['14']

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npm test
      - run: eslint-setup
      - run: eslint-run