name: Test

on: [push]

jobs:
  build:
    strategy:
      matrix:
        node: [16.17.0]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npm i -g typescript@4.7.4
      - run: npm run test-node
      - run: npm run eslint-setup
      - run: npm run eslint-run
      - run: tsc -v
      - run: tsc